Make PyType::name abi3 compatible
PyO3/pyo3 pull request #1166
Opened 2020-09-08 12:59 UTC by alex

2020-09-08 13:43 UTC, kngwyu commented
Some points:
- How about `__qualname__`?
- If we have to extract String, we don't have to `Cow<str>`. This is a minor API and complete compatibility is not required. 
- As the same reason above, we can return `PyResult` if it is needed.

2020-09-08 13:45 UTC, alex commented
Ah yes, `__qualname__` looks much better!

2020-09-08 14:54 UTC, kngwyu requested changes
Thanks, suggested some minor changes

2020-09-08 14:54 UTC, kngwyu commented on src/err.rs
> +                .unwrap_or_else(|_| Cow::Borrowed(self.from.get_type().name())),
```suggestion
                .unwrap_or_else(|_| self.from.get_type().name().into()),
```

2020-09-08 14:54 UTC, kngwyu commented on src/types/typeobject.rs
> +            .expect("__qualname__ not a string")
How about returning `PyResult<&str>`?
It's not fun to see the program crashed in such a trivial operation.
```suggestion
    pub fn name(&self) -> PyResult<&str> {
        self.getattr("__qualname__")?.extract()
```

2020-09-08 15:28 UTC, kngwyu commented on tests/test_methods.rs
> +        Ok(format!("{}.method()!", cls.name().unwrap()))
Just `?` would work

2020-09-08 15:29 UTC, alex commented
sorry this has taken so many revisions

2020-09-09 05:15 UTC, kngwyu approved these changes

2020-09-09 05:16 UTC, kngwyu commented
Thanks!

2020-09-09 05:16 UTC, merged