Define missing import APIs
PyO3/pyo3 pull request #1475
Opened 2021-03-06 18:34 UTC by indygreg

I need some of these APIs for the pyembed crate (used as part of
PyOxidizer). I figured I might as well define them all.

All these APIs are limited.

I don't have a PyPy install with a shared library to test. We may need to disable these when targeting PyPy.

2021-03-06 22:53 UTC, davidhewitt requested changes
Thanks for adding these. Can they please be located in `src/ffi/cpython/import.rs`?

We try to match the cpython header structure as much as possible to make it easier to diff against upstream changes.

If you're willing to put the definitions as the same order as they currently are [in the cpython header](https://github.com/python/cpython/blob/master/Include/import.h), that'd also be much appreciated.

2021-03-06 22:53 UTC, davidhewitt commented on src/ffi/import.rs
> +extern "C" {
This extern block contains `pub static mut` so it's going to need `#[cfg_attr(windows, link(name = "pythonXY"))]`

2021-03-07 11:07 UTC, davidhewitt commented
Also can confirm that none of these APIs appear to exist for PyPy.

2021-03-08 09:02 UTC, kngwyu reviewed
Thanks. As David says, please consider placing some APIs in `cpython` mod. We're refactoring the FFI module in that way (https://github.com/PyO3/pyo3/issues/1289).

2021-03-09 00:50 UTC, indygreg commented on src/ffi/cpython/import.rs
> +    pub fn PyImport_ExtendInittab(newtab: *mut _inittab) -> c_int;
For some reason I'm getting a compiler warning about `PyImport_ExtendInittab()` being unused, so I suppressed this. Unsure why. Maybe the presence of the `pub static mut` above triggers it?

2021-03-09 00:52 UTC, indygreg commented on src/ffi/cpython/import.rs
> +    pub fn PyImport_ExtendInittab(newtab: *mut _inittab) -> c_int;
Yeah, that was it. I moved this to its own block 🤷‍♂️

2021-03-09 08:17 UTC, davidhewitt reviewed
Thanks! Just a final couple of tweaks needed before merging.

Strange, I can't reproduce the unused code warning if I remove those two attributes from the `static mut` variables...

2021-03-09 08:17 UTC, davidhewitt commented on src/ffi/cpython/import.rs
> +    #[allow(unused)]
I don't think that this is needed?

```suggestion
```

2021-03-09 08:17 UTC, davidhewitt commented on src/ffi/cpython/import.rs
> +    #[allow(unused)]
Likewise here.

```suggestion
```

2021-03-09 08:17 UTC, davidhewitt commented on src/ffi/cpython/import.rs
> +    pub initfun: Option<unsafe extern "C" fn()>,
@kngwyu's original comment still stands here - looks like this is missing the return type:

```suggestion
    pub initfun: Option<unsafe extern "C" fn() -> *mut PyObject>,
```

2021-03-09 10:32 UTC, nw0 reviewed
I think the current comments cover everything in import.h from CPython master.

2021-03-09 10:32 UTC, nw0 commented on src/ffi/cpython/import.rs
> +
```suggestion

// skipped PyInit__imp

```

2021-03-09 10:32 UTC, nw0 commented on src/ffi/cpython/import.rs
> +    pub fn _PyImport_FixupExtensionObject(
Am I missing something or is this def the same for Py_3_7 and not(Py_3_7) ?

2021-03-09 10:33 UTC, nw0 commented on CHANGELOG.md
> +- Add FFI definitions from `cpython/import.h`.
```suggestion
- Add FFI definitions from `cpython/import.h`. [#1475](https://github.com/PyO3/pyo3/pull/1475)
```

2021-03-09 21:34 UTC, davidhewitt commented on src/ffi/cpython/import.rs
> +    ) -> c_int;
Good catch @nw0 - looks like for Python 3.6 this had one fewer arguments:

https://github.com/python/cpython/blob/a64de63248267acec87a3ffb6de66ee7008977b2/Include/import.h#L107
```suggestion
    pub fn _PyImport_FixupExtensionObject(
        a: *mut PyObject,
        b: *mut PyObject,
        c: *mut PyObject,
    ) -> c_int;
```

2021-04-21 19:57 UTC, davidhewitt commented
@indygreg thanks for pushing this PR along to this point; I'm going to take it over and push a commit shortly to finish it off as part of some tidy-ups I'm doing for the 0.14 release.

2021-04-21 21:01 UTC, davidhewitt approved these changes

2021-04-22 21:25 UTC, merged