Fix memory leak when calling Python from Rust
PyO3/pyo3 pull request #1806
Opened 2021-08-17 21:36 UTC by pschafhalter

`Python::run_code` transforms the Rust code string to an owned pointer. The owned pointer isn't dereferenced, which results in a memory leak when calling Python from Rust.

This PR adds a missing `Py_DECREF` call on the owned pointer which fixes the memory leak.

Fixes #1801.

Thanks to @mejrs for the tip on the fix.

2021-08-17 22:11 UTC, mejrs approved these changes
Thanks!

> The owned pointer isn't dereferenced

That's not what `Py_DECREF` does (see https://docs.python.org/3/c-api/refcounting.html for more on refcounting).

What happened here was that the raw pointer never had its reference count decremented, so the inner value was leaked and never deallocated. It's similar to `mem::forget`'ing a `Rc` in Rust.

2021-08-17 22:16 UTC, pschafhalter commented
Thanks for the correction! Updated the comment on the PR

2021-08-18 04:54 UTC, birkenfeld requested changes

2021-08-18 04:54 UTC, birkenfeld commented on CHANGELOG.md
> +- Add missing `Py_DECREF` to fix memory leak when calling Python from Rust. [#1806](https://github.com/PyO3/pyo3/pull/1806)
This should explicitly state which function contained the bug.

2021-08-18 06:20 UTC, birkenfeld approved these changes
LGTM, thanks! @davidhewitt needs cherry-pick to 0.14...

2021-08-18 06:28 UTC, messense approved these changes
Thanks!

2021-08-18 06:52 UTC, merged

2021-08-18 07:02 UTC, messense commented
[auto-merge](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) works! 🎉