more macro hygiene cleanup: test #[pymethods] and more arg parsing and protos
PyO3/pyo3 pull request #1843
Opened 2021-08-28 14:44 UTC by birkenfeld

After this PR and the two previous ones (#1841, #1842), no non-doc usages of `pyo3::` remain in the macros-backend crate or the main crate.

2021-08-28 23:38 UTC, mejrs requested changes
Looks like unimplemented isn't hygienic before 1.50 - https://github.com/rust-lang/rust/pull/78343

2021-08-28 23:38 UTC, mejrs commented on tests/test_proc_macro_hygiene.rs
> +        ::std::unimplemented!()
```suggestion
        ::std::panic!("unimplemented isn't hygienic before 1.50")
```

2021-08-28 23:38 UTC, mejrs commented on tests/test_proc_macro_hygiene.rs
> +        ::std::unimplemented!()
```suggestion
        ::std::panic!("unimplemented isn't hygienic before 1.50")
```

2021-08-29 06:31 UTC, birkenfeld commented
> Looks like unimplemented isn't hygienic before 1.50 - [rust-lang/rust#78343](https://github.com/rust-lang/rust/pull/78343)

Interesting, thanks for finding that :)

2021-08-29 10:26 UTC, davidhewitt approved these changes
💯 awesome work on building out this test @birkenfeld @mejrs !

2021-08-29 10:26 UTC, merged