packaging: formal support for Python 3.10
PyO3/pyo3 pull request #1889
Opened 2021-09-26 12:52 UTC by davidhewitt

This PR goes through the FFI changes listed in #1781, and also adds an `abi3-py310` feature.

Given that we have also tested Python 3.10 on CI for a long time, and this PR adds the documented C API changes, I think we can call Python 3.10 officially supported now.

I also made a tidy-up pass to use `_Py_NewRef` in expressions in a bunch of places, because imo it's nicer than calling `Py_INCREF` in a separate satement. And we can define `_Py_NewRef` on all supported Python versions (not just 3.10).

Closes #1781 

(The PEP 622 support is tracked separately in #1714 - I don't think we'll have this ready by the time 3.10 is released.)

2021-09-26 14:36 UTC, davidhewitt commented on CHANGELOG.md
> +- Add `abi3-py310` feature. [#1885](https://github.com/PyO3/pyo3/pull/1885)
```suggestion
- Add `abi3-py310` feature. [#1889](https://github.com/PyO3/pyo3/pull/1889)
```

2021-09-26 23:15 UTC, mejrs requested changes
Thanks!..just two nits

2021-09-26 23:15 UTC, mejrs commented on src/ffi/modsupport.rs
> +        arg3: *mut PyObject,
```suggestion
        module: *mut PyObject,
        name: *const c_char,
        value: *mut PyObject,
```

That's the names these have in the documentation

2021-09-26 23:15 UTC, mejrs commented on src/ffi/object.rs
> +#[repr(C)]
```suggestion
#[repr(C)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
```

2021-09-29 16:45 UTC, mejrs approved these changes

2021-09-29 18:36 UTC, merged