docs: Clarify the requirement to install nox before building documentation
PyO3/pyo3 pull request #3812
Opened 2024-02-08 16:42 UTC by Hamatti

Installing nox was mentioned in a later section when building the user guide but not at this point earlier in the guide where nox was needed for the first time.

I ran into this when I was first attempting to build the docs and it took me a moment to realize I had to install it as a global tool, separate from the dependencies of this project.

2024-02-10 14:13 UTC, davidhewitt requested changes
Thank you 👍 

Mind rebasing this? Unfortunately you picked the one day every 6 weeks where CI breaks because rust stable got updated and our UI test output changes 🙈

2024-02-10 14:13 UTC, davidhewitt approved these changes

2024-02-10 14:21 UTC, Hamatti commented
> Thank you 👍
> 
> Mind rebasing this? Unfortunately you picked the one day every 6 weeks where CI breaks because rust stable got updated and our UI test output changes 🙈

Sure thing!

2024-02-10 17:43 UTC, Hamatti commented
Should I worry about the failing checks?

2024-02-10 22:08 UTC, davidhewitt commented
Thanks!

> Should I worry about the failing checks?

Benchmarks have a little bit of volatility at the moment, I hope to quieten that sometime.

Nightly Rust has just recently noticed that we're not using a particular internal function, but I expect we _will_ use it soon so that check will go green soon enough.

Neither are anything to worry about 😄

2024-02-11 01:55 UTC, davidhewitt commented
... and PyPy has [a known flaky crash](https://github.com/PyO3/pyo3/issues/3766) 🙃

2024-02-11 02:52 UTC, merged